const pool = require("../config/database");

async function create({ conferenceId, name, description }, db = pool) {
    const [rows] = await db.execute(
        `INSERT INTO departments (conference_id, name, description) VALUES ($1, $2, $3) RETURNING id`,
        [conferenceId, name, description || null]
    );
    return rows[0].id;
}

/**
 * Seeds a standard set of MUN organizing departments the first time the
 * Team page's Departments tab loads and finds none -- so organizers get a
 * sensible starting point (Logistics, Finance, etc.) instead of an empty
 * list with nothing to attach team members to. ON CONFLICT DO NOTHING is
 * safe here (unlike some other tables in this codebase): departments has a
 * real UNIQUE(conference_id, name) constraint, so this is idempotent and
 * safe to call again after the organizer has already added/renamed some.
 */
const DEFAULT_DEPARTMENTS = [
    "Logistics", "Registration", "Finance", "Media & Public Relations",
    "Hospitality", "IT & Technical Support", "Delegate Affairs"
];

async function autoGenerateDefaults(conferenceId, db = pool) {
    for (const name of DEFAULT_DEPARTMENTS) {
        await db.execute(
            `INSERT INTO departments (conference_id, name) VALUES ($1, $2) ON CONFLICT (conference_id, name) DO NOTHING`,
            [conferenceId, name]
        );
    }
    return listByConference(conferenceId, db);
}

async function findById(id, db = pool) {
    const [rows] = await db.execute(`SELECT * FROM departments WHERE id = $1`, [id]);
    return rows[0] || null;
}

async function listByConference(conferenceId, db = pool) {
    const [rows] = await db.query(
        `SELECT d.*, (SELECT COUNT(*) FROM organizer_access a WHERE a.department_id = d.id) AS member_count
         FROM departments d WHERE d.conference_id = $1 ORDER BY d.name ASC`,
        [conferenceId]
    );
    return rows;
}

async function update(id, { name, description }, db = pool) {
    const setClauses = [];
    const params = [];
    let idx = 1;
    if (name !== undefined) { setClauses.push(`name = $${idx++}`); params.push(name); }
    if (description !== undefined) { setClauses.push(`description = $${idx++}`); params.push(description); }

    if (setClauses.length === 0) return findById(id, db);

    params.push(id);
    await db.execute(`UPDATE departments SET ${setClauses.join(", ")} WHERE id = $${idx}`, params);
    return findById(id, db);
}

async function remove(id, db = pool) {
    await db.execute(`DELETE FROM departments WHERE id = $1`, [id]);
}

module.exports = { create, findById, listByConference, update, remove, autoGenerateDefaults };
