const pool = require("../config/database");

async function createDay({ conferenceId, dayDate, label }, db = pool) {
    const [rows] = await db.execute(
        `INSERT INTO conference_schedule_days (conference_id, day_date, label) VALUES ($1, $2, $3)
         RETURNING id`,
        [conferenceId, dayDate, label || null]
    );
    return rows[0].id;
}

async function findDayById(id, db = pool) {
    const [rows] = await db.execute(`SELECT * FROM conference_schedule_days WHERE id = $1`, [id]);
    return rows[0] || null;
}

/**
 * Seeds one row per calendar day between the conference's own start/end
 * dates -- called by the frontend the first time the Schedule page loads
 * and finds zero days, so organizers get "Day 1/Day 2/Day 3" already
 * there instead of having to add each day by hand when the conference's
 * length is already known from Settings. Skips any date that's already
 * been added (UNIQUE(conference_id, day_date) would reject it anyway),
 * so this is safe to call repeatedly / after some days already exist.
 */
async function autoGenerateDays(conferenceId, startDate, endDate, db = pool) {
    const [existingRows] = await db.execute(
        `SELECT day_date FROM conference_schedule_days WHERE conference_id = $1`,
        [conferenceId]
    );
    const existingDates = new Set(existingRows.map((r) => new Date(r.day_date).toISOString().slice(0, 10)));

    const cursor = new Date(startDate);
    const end = new Date(endDate);
    let dayNumber = 1;
    const createdIds = [];

    while (cursor <= end) {
        const dateStr = cursor.toISOString().slice(0, 10);
        if (!existingDates.has(dateStr)) {
            const id = await createDay({ conferenceId, dayDate: dateStr, label: `Day ${dayNumber}` }, db);
            createdIds.push(id);
        }
        dayNumber += 1;
        cursor.setUTCDate(cursor.getUTCDate() + 1);
    }
    return createdIds;
}

async function removeDay(id, db = pool) {
    await db.execute(`DELETE FROM conference_schedule_days WHERE id = $1`, [id]);
}

async function createEvent(
    { scheduleDayId, committeeId, title, type, location, startTime, endTime, status },
    db = pool
) {
    const [rows] = await db.execute(
        `INSERT INTO schedule_events (schedule_day_id, committee_id, title, type, location, start_time, end_time, status)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
         RETURNING id`,
        [
            scheduleDayId, committeeId || null, title, type || "general_event",
            location || null, startTime, endTime, status || "scheduled"
        ]
    );
    return rows[0].id;
}

async function findEventById(id, db = pool) {
    const [rows] = await db.execute(`SELECT * FROM schedule_events WHERE id = $1`, [id]);
    return rows[0] || null;
}

const UPDATABLE_EVENT_FIELDS = {
    title: "title", type: "type", location: "location", startTime: "start_time",
    endTime: "end_time", status: "status", committeeId: "committee_id"
};

async function updateEvent(id, data, db = pool) {
    const setClauses = [];
    const params = [];

    for (const [key, column] of Object.entries(UPDATABLE_EVENT_FIELDS)) {
        if (data[key] !== undefined) {
            params.push(data[key]);
            setClauses.push(`${column} = $${params.length}`);
        }
    }

    if (setClauses.length === 0) return findEventById(id, db);

    params.push(id);
    await db.execute(`UPDATE schedule_events SET ${setClauses.join(", ")} WHERE id = $${params.length}`, params);
    return findEventById(id, db);
}

async function removeEvent(id, db = pool) {
    await db.execute(`DELETE FROM schedule_events WHERE id = $1`, [id]);
}

async function listForConference(conferenceId, db = pool) {
    const [days] = await db.execute(
        `SELECT * FROM conference_schedule_days WHERE conference_id = $1 ORDER BY day_date ASC`,
        [conferenceId]
    );
    if (days.length === 0) return [];

    const dayIds = days.map((d) => d.id);
    const [events] = await db.query(
        `SELECT se.*, c.name AS committee_name
         FROM schedule_events se
         LEFT JOIN committees c ON c.id = se.committee_id
         WHERE se.schedule_day_id = ANY($1::bigint[])
         ORDER BY se.start_time ASC`,
        [dayIds]
    );

    return days.map((day) => ({
        ...day,
        events: events.filter((e) => e.schedule_day_id === day.id)
    }));
}

module.exports = {
    createDay, findDayById, removeDay, createEvent, findEventById, updateEvent, removeEvent, listForConference,
    autoGenerateDays
};
